name: Run Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js with caching
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Match this with the version you're using locally
          cache: "npm" # Cache npm dependencies to speed up builds

      # Clear npm cache (from your original workflow)
      - name: Clear npm cache
        run: npm cache clean --force

      # Install dependencies using npm ci (for consistent installation)
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test

      # Archive test results (optional, for debugging)
      - name: Archive test results
        if: always() # Runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            *.xml
            *.log

      # Debug open handles (from your original, runs only on failure)
      - name: Debug open handles
        if: failure()
        run: npm test -- --detectOpenHandles
